-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS "recipe_ingredient" CASCADE;
DROP TABLE IF EXISTS "ingredient" CASCADE;
DROP TABLE IF EXISTS "image" CASCADE;
DROP TABLE IF EXISTS "recipe" CASCADE;
