-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS "meal_recipe" CASCADE;
DROP TABLE IF EXISTS "recipe_indigrent" CASCADE;
DROP TABLE IF EXISTS "indigrent" CASCADE;
DROP TABLE IF EXISTS "meal" CASCADE;
DROP TABLE IF EXISTS "image" CASCADE;
DROP TABLE IF EXISTS "recipe" CASCADE;
DROP TABLE IF EXISTS "category" CASCADE;
