-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS "rating" CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS "beer" CASCADE;
DROP TABLE IF EXISTS "style" CASCADE;
DROP TABLE IF EXISTS "brewery" CASCADE;
